---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
        exclude: '{{cookiecutter.project_slug}}'
      - id: check-builtin-literals
        exclude: '{{cookiecutter.project_slug}}'
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: debug-statements
        exclude: '{{cookiecutter.project_slug}}'
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: no-commit-to-branch
        args: [--branch, master]
      - id: trailing-whitespace

  - repo: https://github.com/ambv/black
    rev: 21.12b0
    hooks:
      - id: black
        additional_dependencies: [toml]

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        exclude: '{{cookiecutter.project_slug}}'

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.3
    hooks:
      - id: yamllint

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.30.0
    hooks:
      - id: markdownlint
