[tool.commitizen]
name = 'cz_conventional_commits'
version = '0.0.0'

[tool.black]
line-length = 79
target-version = ['py39']
exclude = '{{cookiecutter.project_slug}}'

[tool.flake8]
exclude = '{{cookiecutter.project_slug}}'
