---
name: Tests

on:  # yamllint disable-line rule:truthy
  push:
  pull_request:

jobs:
  Tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: make install
      - name: Cache pre-commit
        uses: actions/cache@v2
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-2-${hashFile('.pre-commit-config.yaml')}
          restore-keys: |
            pre-commit-2-
      - name: Lint
        run: SKIP=no-commit-to-branch make lint
      - name: Test
        run: make test
      - name: Test documentation
        run: make build-docs
